### ISSUE TITLE
Missing announcement for migration of https://github.com/sonatype/helm3-charts to this repo

### ISSUE THREAD

**Issue by mpailloncy** [sonatype/nxrm3-helm-repository#17]
It looks like the source of the latest versions of Helm chart sonatype/nexus-repository-manager are hosted inside this repo.
If my assumption is correct, then there should be some docs/announcement about it as it's misleading for end users.

**Comment by mpailloncy** [comment]
Raising this as we faced an issue with tags 41.1.1, 41.1.2 and 41.1.3 as they don't contain a fix for https://github.com/sonatype/helm3-charts/pull/195 (missing ingressClassName for Docker/OCI repositories).
Looks like this fix have been lost during the migration or something ? 

Anyways, for those needing a workaround, version 41.0.0 does contain this fix.

**Comment by bobotimi** [comment]
@mpailloncy Thank you for your comment. Indeed we have a copy of [this](https://github.com/sonatype/helm3-charts/tree/main/charts/nexus-repository-manager) Helm chart located in [this](https://github.com/sonatype/nxrm3-helm-repository) repository. However, it  has not yet been officially moved and this is why it is still present [here](https://github.com/sonatype/helm3-charts/tree/main/charts/nexus-repository-manager) and also the reason why there was no announcement. However, we do appreciate that having this particular Helm chart in two locations causes confusion and as such we'll be removing it from this repository (i.e. [nxrm3-helm-repository](https://github.com/sonatype/nxrm3-helm-repository)) momentarily. Please continue to use [helm3-charts](https://github.com/sonatype/helm3-charts/tree/main/charts/nexus-repository-manager).

If there's any such migration in the future, be rest assured that it'll be in just one location and we'll communicate accordingly.

Kind regards
